/**
 * SSB WAT Simulator — Word Bank
 * 1000+ curated words across all WAT categories:
 * Positive, Negative, Neutral, Abstract, Leadership, Military,
 * Emotional, Everyday Life, Psychological Trigger words.
 */
const WORD_BANK = [
  // === LEADERSHIP ===
  "Leader", "Command", "Authority", "Vision", "Strategy",
  "Inspire", "Guide", "Mentor", "Delegate", "Decision",
  "Initiative", "Ambition", "Influence", "Motivate", "Direct",
  "Govern", "Supervise", "Empower", "Champion", "Mobilize",
  "Coordinate", "Organize", "Prioritize", "Execute", "Resolve",
  "Dictate", "Dominate", "Control", "Manage", "Steer",

  // === MILITARY ===
  "Soldier", "Duty", "Mission", "Regiment", "Battalion",
  "Patrol", "Rank", "Uniform", "Salute", "Honor",
  "Garrison", "Frontline", "Combat", "Troop", "Platoon",
  "Valor", "Allegiance", "Discipline", "Fortify", "Siege",
  "Ambush", "Deploy", "Recon", "Terrain", "Bunker",
  "Artillery", "Infantry", "Cavalry", "Command Post", "Barracks",
  "Sniper", "Guerilla", "Sabotage", "Objective", "Flank",
  "Retreat", "Advance", "Surrender", "Victory", "Defeat",
  "War", "Battle", "Weapon", "Enemy", "Ally",
  "Ceasefire", "Armistice", "Casualty", "Martyr", "Sacrifice",

  // === POSITIVE ===
  "Success", "Achievement", "Growth", "Progress", "Hope",
  "Joy", "Peace", "Happiness", "Prosperity", "Harmony",
  "Confidence", "Strength", "Wisdom", "Integrity", "Loyalty",
  "Kindness", "Generosity", "Compassion", "Gratitude", "Love",
  "Courage", "Perseverance", "Determination", "Resilience", "Endurance",
  "Trust", "Faith", "Optimism", "Enthusiasm", "Passion",
  "Freedom", "Justice", "Equality", "Unity", "Solidarity",
  "Creativity", "Innovation", "Excellence", "Brilliance", "Talent",
  "Dedication", "Commitment", "Honesty", "Transparency", "Sincerity",
  "Patience", "Humility", "Empathy", "Respect", "Dignity",
  "Opportunity", "Potential", "Capability", "Skill", "Mastery",
  "Reward", "Recognition", "Glory", "Honor", "Pride",

  // === NEGATIVE ===
  "Failure", "Defeat", "Loss", "Fear", "Anxiety",
  "Anger", "Hate", "Jealousy", "Envy", "Greed",
  "Betrayal", "Deception", "Corruption", "Injustice", "Oppression",
  "Violence", "Aggression", "Cruelty", "Abuse", "Neglect",
  "Suffering", "Pain", "Grief", "Despair", "Depression",
  "Shame", "Guilt", "Regret", "Remorse", "Humiliation",
  "Cowardice", "Weakness", "Laziness", "Procrastination", "Apathy",
  "Poverty", "Hunger", "Disease", "Crime", "Corruption",
  "Loneliness", "Isolation", "Abandonment", "Rejection", "Exclusion",
  "Death", "Disaster", "Tragedy", "Catastrophe", "Crisis",
  "Terrorism", "War", "Conflict", "Chaos", "Disorder",
  "Addiction", "Obsession", "Compulsion", "Manipulation", "Exploitation",

  // === NEUTRAL / EVERYDAY LIFE ===
  "Home", "Family", "Mother", "Father", "Brother",
  "Sister", "Friend", "Neighbor", "Teacher", "Student",
  "Work", "School", "Office", "Hospital", "Market",
  "Road", "Train", "Car", "Bus", "Bicycle",
  "Food", "Water", "Air", "Fire", "Earth",
  "Book", "Pen", "Paper", "Computer", "Phone",
  "Money", "Bank", "Shop", "Business", "Trade",
  "Morning", "Night", "Day", "Week", "Year",
  "Rain", "Sun", "Wind", "Snow", "Cloud",
  "River", "Mountain", "Ocean", "Forest", "Desert",
  "City", "Village", "Town", "Country", "World",
  "Garden", "Park", "Field", "Farm", "Factory",
  "Door", "Window", "Room", "Floor", "Roof",
  "Clothes", "Shoes", "Watch", "Bag", "Key",
  "Music", "Dance", "Art", "Sport", "Game",
  "News", "Radio", "Television", "Internet", "Newspaper",
  "Cooking", "Eating", "Sleeping", "Walking", "Running",
  "Meeting", "Party", "Wedding", "Festival", "Holiday",
  "Marriage", "Child", "Baby", "Old", "Young",

  // === ABSTRACT ===
  "Time", "Space", "Truth", "Beauty", "Reality",
  "Dream", "Imagination", "Thought", "Mind", "Soul",
  "Spirit", "Consciousness", "Existence", "Universe", "Infinity",
  "Destiny", "Fate", "Chance", "Luck", "Karma",
  "Purpose", "Meaning", "Value", "Principle", "Belief",
  "Idea", "Concept", "Theory", "Logic", "Reason",
  "Emotion", "Feeling", "Instinct", "Intuition", "Perception",
  "Memory", "Experience", "Knowledge", "Understanding", "Wisdom",
  "Change", "Transformation", "Evolution", "Revolution", "Progress",
  "Order", "Chaos", "Balance", "Harmony", "Conflict",
  "Power", "Energy", "Force", "Will", "Desire",
  "Hope", "Faith", "Doubt", "Certainty", "Mystery",
  "Culture", "Tradition", "Heritage", "Identity", "Belonging",
  "Morality", "Ethics", "Justice", "Right", "Wrong",
  "Good", "Evil", "Light", "Darkness", "Shadow",

  // === EMOTIONAL / PSYCHOLOGICAL TRIGGERS ===
  "Longing", "Nostalgia", "Melancholy", "Euphoria", "Panic",
  "Terror", "Rage", "Ecstasy", "Sorrow", "Bliss",
  "Dread", "Awe", "Wonder", "Shock", "Surprise",
  "Confusion", "Clarity", "Frustration", "Relief", "Excitement",
  "Boredom", "Curiosity", "Obsession", "Desire", "Repulsion",
  "Admiration", "Contempt", "Pity", "Envy", "Pride",
  "Contentment", "Satisfaction", "Disappointment", "Elation", "Misery",
  "Affection", "Resentment", "Forgiveness", "Acceptance", "Denial",
  "Attachment", "Detachment", "Dependency", "Independence", "Vulnerability",
  "Trauma", "Healing", "Recovery", "Breakdown", "Breakthrough",
  "Pressure", "Stress", "Burnout", "Overwhelm", "Exhaustion",
  "Celebration", "Mourning", "Gratitude", "Bitterness", "Serenity",

  // === RESPONSIBILITY / CHARACTER ===
  "Responsibility", "Accountability", "Integrity", "Character", "Virtue",
  "Moral", "Ethical", "Principled", "Righteous", "Upright",
  "Trustworthy", "Reliable", "Dependable", "Steadfast", "Consistent",
  "Selfless", "Selfishness", "Sacrifice", "Service", "Seva",
  "Obedience", "Rebellion", "Compliance", "Defiance", "Submission",
  "Perseverance", "Willpower", "Grit", "Tenacity", "Fortitude",
  "Adaptability", "Flexibility", "Rigidity", "Stubbornness", "Persistence",
  "Humility", "Arrogance", "Modesty", "Vanity", "Ego",
  "Compassion", "Sympathy", "Empathy", "Apathy", "Indifference",
  "Generosity", "Stinginess", "Kindness", "Cruelty", "Fairness",

  // === RISK / CHALLENGE ===
  "Risk", "Challenge", "Obstacle", "Barrier", "Hurdle",
  "Danger", "Threat", "Hazard", "Uncertainty", "Unknown",
  "Adventure", "Exploration", "Discovery", "Expedition", "Journey",
  "Trial", "Test", "Exam", "Evaluation", "Assessment",
  "Problem", "Solution", "Answer", "Question", "Dilemma",
  "Gamble", "Bet", "Stake", "Investment", "Return",
  "Crisis", "Emergency", "Disaster", "Survival", "Rescue",
  "Pressure", "Deadline", "Urgency", "Priority", "Focus",
  "Breakthrough", "Setback", "Recovery", "Bounce", "Fall",
  "Climb", "Descent", "Summit", "Base", "Peak",

  // === NATION / SOCIETY ===
  "Nation", "Country", "Patriotism", "Democracy", "Republic",
  "Constitution", "Law", "Order", "Police", "Court",
  "Government", "Parliament", "Election", "Vote", "Citizen",
  "Society", "Community", "Culture", "Religion", "Belief",
  "Economy", "Development", "Infrastructure", "Education", "Health",
  "Poverty", "Wealth", "Inequality", "Discrimination", "Reservation",
  "Minority", "Majority", "Rights", "Duties", "Freedom",
  "Independence", "Partition", "History", "Heritage", "Tradition",
  "Border", "Territory", "Sovereignty", "Diplomacy", "Treaty",
  "Alliance", "Sanction", "Embargo", "War", "Peace",
  "Refugee", "Migrant", "Exile", "Diaspora", "Homeland",
  "Unity", "Diversity", "Integration", "Segregation", "Harmony",

  // === NATURE / ENVIRONMENT ===
  "Nature", "Environment", "Ecology", "Biodiversity", "Ecosystem",
  "Climate", "Pollution", "Conservation", "Sustainability", "Renewal",
  "Wilderness", "Wildlife", "Species", "Extinction", "Preservation",
  "Earthquake", "Flood", "Drought", "Storm", "Tsunami",
  "Volcano", "Lightning", "Thunder", "Rainbow", "Horizon",
  "Sunset", "Sunrise", "Moonlight", "Starlight", "Darkness",
  "Tree", "Flower", "Grass", "Soil", "Stone",
  "Ocean", "Wave", "Tide", "Current", "Depth",
  "Mountain", "Valley", "Plateau", "Cave", "Cliff",
  "Desert", "Oasis", "Jungle", "Savanna", "Tundra",

  // === SPORTS / PHYSICAL ===
  "Sport", "Competition", "Tournament", "Championship", "Medal",
  "Training", "Fitness", "Strength", "Agility", "Speed",
  "Endurance", "Stamina", "Flexibility", "Balance", "Coordination",
  "Win", "Lose", "Draw", "Score", "Goal",
  "Team", "Captain", "Coach", "Player", "Champion",
  "Marathon", "Sprint", "Jump", "Throw", "Swim",
  "Cricket", "Football", "Hockey", "Boxing", "Wrestling",
  "Olympics", "Trophy", "Gold", "Silver", "Bronze",
  "Record", "Benchmark", "Standard", "Performance", "Improvement",
  "Opponent", "Rival", "Competitor", "Teammate", "Partner",

  // === SCIENCE / TECHNOLOGY ===
  "Science", "Technology", "Research", "Innovation", "Discovery",
  "Invention", "Patent", "Experiment", "Data", "Analysis",
  "Artificial Intelligence", "Robotics", "Space", "Satellite", "Rocket",
  "Medicine", "Surgery", "Vaccine", "Cure", "Diagnosis",
  "Physics", "Chemistry", "Biology", "Mathematics", "Engineering",
  "Machine", "Engine", "Power", "Energy", "Fuel",
  "Digital", "Cyber", "Network", "Connection", "Information",
  "Future", "Past", "Present", "Evolution", "Revolution",
  "Atom", "Molecule", "Cell", "Gene", "DNA",
  "Planet", "Star", "Galaxy", "Black Hole", "Cosmos",

  // === RELATIONSHIPS ===
  "Relationship", "Bond", "Connection", "Attachment", "Separation",
  "Love", "Hate", "Trust", "Betrayal", "Forgiveness",
  "Marriage", "Divorce", "Family", "Friendship", "Rivalry",
  "Mentor", "Protege", "Parent", "Child", "Sibling",
  "Partner", "Colleague", "Stranger", "Enemy", "Hero",
  "Communication", "Dialogue", "Argument", "Negotiation", "Agreement",
  "Support", "Conflict", "Cooperation", "Competition", "Collaboration",
  "Respect", "Disrespect", "Appreciation", "Criticism", "Feedback",
  "Reunion", "Farewell", "Goodbye", "Welcome", "Belonging",
  "Loneliness", "Company", "Solitude", "Crowd", "Community",

  // === ADDITIONAL DIVERSE ===
  "Beginner", "Expert", "Amateur", "Professional", "Master",
  "Opportunity", "Obstacle", "Success", "Struggle", "Triumph",
  "Ambition", "Contentment", "Restlessness", "Stability", "Movement",
  "Tradition", "Modernity", "Simplicity", "Complexity", "Clarity",
  "Plan", "Action", "Result", "Consequence", "Impact",
  "Beginning", "End", "Middle", "Transition", "Turning Point",
  "Silence", "Noise", "Rhythm", "Melody", "Harmony",
  "Color", "Shape", "Form", "Structure", "Pattern",
  "Weight", "Burden", "Load", "Pressure", "Release",
  "Fight", "Flight", "Freeze", "Surrender", "Resist",
  "Hunger", "Thirst", "Satiety", "Craving", "Indulgence",
  "Discipline", "Indiscipline", "Order", "Chaos", "System",
  "Reward", "Punishment", "Consequence", "Incentive", "Deterrent",
  "Speed", "Patience", "Urgency", "Calm", "Rush",
  "Individual", "Collective", "Group", "Mass", "Nation",

  // === PHILOSOPHICAL / DEEP ===
  "Existence", "Nothingness", "Being", "Becoming", "Transcendence",
  "Absolute", "Relative", "Objective", "Subjective", "Universal",
  "Liberation", "Bondage", "Enlightenment", "Ignorance", "Awakening",
  "Suffering", "Pleasure", "Pain", "Bliss", "Equanimity",
  "Attachment", "Detachment", "Desire", "Renunciation", "Liberation",
  "Creation", "Destruction", "Preservation", "Transformation", "Manifestation",
  "Divine", "Mortal", "Sacred", "Profane", "Holy",
  "Conscience", "Consciousness", "Subconscious", "Unconscious", "Awareness",
  "Ego", "Id", "Superego", "Persona", "Shadow",
  "Archetype", "Symbol", "Myth", "Legend", "Story",

  // === CAREER / AMBITION ===
  "Career", "Profession", "Vocation", "Calling", "Purpose",
  "Promotion", "Demotion", "Transfer", "Posting", "Deputation",
  "Retirement", "Pension", "Service", "Term", "Tenure",
  "Salary", "Bonus", "Incentive", "Appraisal", "Review",
  "Interview", "Selection", "Rejection", "Appointment", "Resignation",
  "Leadership", "Followership", "Teamwork", "Solo", "Partnership",
  "Goal", "Target", "Milestone", "Achievement", "Benchmark",
  "Learning", "Unlearning", "Relearning", "Growth", "Stagnation",
  "Mentor", "Guidance", "Coaching", "Training", "Development",
  "Vision", "Mission", "Strategy", "Tactic", "Plan",

  // === SSB-SPECIFIC TRIGGERS ===
  "OLQ", "PPDT", "GTO", "Interview", "Psychologist",
  "Command", "Obstacle", "Group Task", "Planning", "Lecturette",
  "Rank", "Officer", "Cadet", "Academy", "Training",
  "IMA", "OTA", "NDA", "AFMC", "AFA",
  "Army", "Navy", "Air Force", "Para", "NSG",
  "CRPF", "BSF", "CISF", "SSB", "UPSC",
  "Bravery", "Gallantry", "Medal", "Citation", "Commendation",
  "Initiative", "Liveliness", "Stamina", "Determination", "Cooperation",
  "Influence", "Reasoning", "Ability", "Intelligence", "Aptitude",
  "Effective", "Efficient", "Capable", "Confident", "Assertive"
];

export default WORD_BANK;
